# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  pythonInterpreter: C:\Users\newgo\Desktop\ExperimentApi\env\Scripts\python.exe

parameters:
  - name: runTest
    type: boolean
    default: false
    

trigger:
- main
- master

pool:
  name: 'test'

stages:
 - stage: FirstStage
   jobs:
      - job: JobAFromFirstStage
        steps:
         - task: PythonScript@0
           inputs:
            scriptSource: 'inline'
            script: |
              my_list = [1,2,3,4,5]
              print(str([a * a for a in my_list]))
            pythonInterpreter: '${{variables.pythonInterpreter}}'
      - job: JobBFromFirstStage
        steps:
          - script: echo Job B
  
 - stage: SecondStage
   jobs:
      - job: JobAFromSecondStage
        steps:
          - script: echo LOLLLLLOOO
            displayName: Printing LOL
      - job: JobBFromSecondStage
        steps:
          - script: echo kek
            displayName: Printing KEK
    