# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  pythonInterpreter: C:\Users\newgo\Desktop\ExperimentApi\env\Scripts\python.exe

trigger:
- main
- master

pool:
  name: 'test'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: PythonScript@0
  inputs:
    pythonInterpreter: ${{variables.pythonInterpreter}}
    scriptSource: 'inline'
    script: 'print("Hello Yurii")'
  displayName: Test Script 1
- task: PythonScript@0
  inputs:
    pythonInterpreter: ${{variables.pythonInterpreter}}
    scriptSource: 'inline'
    script: 'print("Hello Yurii")'
  displayName: Test Script 2