# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  pythonInterpreter: C:\Users\newgo\Desktop\ExperimentApi\env\Scripts\python.exe

    

trigger:
- main
- master

pool:
  name: 'test'

stages:
  - stage: PreperationEnv
    jobs:
      - job: PreperatePythonEnv
        steps:
          - script: echo Preparation Python env
  
  - stage: DownloadDependencies
    jobs:
      - job: DownloadSDK
        steps:
          - script: echo Downloading SDK
      - job: DownloadGradle
        steps:
          - script: echo Downlading Gradle
      - job: BuildGradle
        steps:
          - script: echo Buidl gradle

  - stage: BuildSoftware
    jobs:
      - job: 
        steps:
          - script: echo Building the project
  
  - stage: DynamicTests
    pool: 
      vmImage: 'Ubuntu-16.04'
    dependsOn: BuildSoftware
    jobs:
      - job: FlashDevices
        steps:
          - script: echo Flashing the devices
      - job: RunDynamicTests
        steps:
          - script: echo Dynamic Tests
  
  - stage: StaticTests
    pool: 
      vmImage: 'macos-10.14'
    dependsOn: BuildSoftware
    jobs:
      - job: RunStaticTests
        steps:
          - script: |
              echo Static Tests
              exit 1
      - job: UnitTests
        dependsOn: RunStaticTests
        steps:
          - script: echo Unit Tests
  
  - stage: Deploy
    pool:
      vmImage: 'Ubuntu-16.04'
    dependsOn:
      - DynamicTests
    jobs:
      - job: 
        steps:
          - script: echo Deploying...
